import "server-only";

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { getPortalCustomerTypeInfo } from "@/lib/portal/customerTypes";
import {
  calculateDerivedMetrics,
  getAccountsForUser,
  getUsersForAccount,
  groupAccountRows,
  normalizeAccountNumber,
  normalizeEmail,
} from "@/lib/portal/normalizeAccounts";

const PORTAL_SOURCE_DIR = path.join(
  process.cwd(),
  "private-source",
  "portal"
);

const WORKBOOK_DATA_PATH = path.join(PORTAL_SOURCE_DIR, "workbook-data.json");

type PortalWorkbookData = {
  people?: PortalWorkbookPerson[];
  accounts?: PortalWorkbookAccount[];
};

export type PortalWorkbookPerson = {
  name: string;
  organization: string;
  accountNumber: string;
  emails: string[];
  division: string;
  artisanLab: string;
  targetedPrograms: string;
  lastOrderShipped: string;
};

export type PortalWorkbookAccount = {
  accountName: string;
  accountNumber: string;
  division: string;
  salesRep: string;
  lastShippedDate: string;
  primaryPalPrivatePay: string;
  primaryPalVsp: string;
  lastLabName: string;
  fullAddress: string;
  phoneNumber: string;
  state: string;
  zipCode: string;
  modernPkgUsage: string;
  modernFrmUsage: string;
  chemClipUsage: string;
  specCheckUsage: string;
  tokaiUsage: string;
  tier: string;
  ppmJobs: number;
  pmJobs: number;
  cmJobs: number;
  ppmSales: number;
  pmSales: number;
  cmSales: number;
  ppmJpd: number;
  pmJpd: number;
  cmJpd: number;
  ppmNlJobs: number;
  pmNlJobs: number;
  cmNlJobs: number;
  pmNlSow: number;
  ppmNlSow: number;
  cmNlSow: number;
  cmSqlJobs: number;
  pmSqlJobs: number;
  ppmSqlJobs: number;
  ppmVspJobs: number;
  pmVspJobs: number;
  cmVspJobs: number;
  ppmVspSow: number;
  pmVspSow: number;
  cmVspSow: number;
  lastShippedDateGlobal: string;
  detectedCustomerTypeCodes?: string[];
  finalCustomerTypeCode?: string;
  mergedRowCount?: number;
  duplicateRowsMerged?: boolean;
  sameNameDifferentAccountWarning?: boolean;
  sameNameAccountNumbers?: string[];
};

export type PortalWorkbookProfile = {
  person: PortalWorkbookPerson;
  account?: PortalWorkbookAccount;
};

const SEQUEL_REBATE_PROGRAM = "sequel rebate";

function toText(value: unknown) {
  if (value === null || value === undefined) return "";
  if (value instanceof Date) return value.toISOString().slice(0, 10);

  return String(value).trim();
}

function toNumber(value: unknown) {
  if (typeof value === "number") return Number.isFinite(value) ? value : 0;

  const parsed = Number(toText(value).replace(/[$,%\s]/g, ""));

  return Number.isFinite(parsed) ? parsed : 0;
}

function toAccountNumber(value: unknown) {
  if (typeof value === "number" && Number.isFinite(value)) {
    return String(Math.trunc(value));
  }

  return toText(value).replace(/\.0$/, "");
}

export function normalizePortalAccountNumber(value: unknown) {
  return normalizeAccountNumber(toAccountNumber(value));
}

function emailList(value: unknown) {
  return toText(value)
    .split(",")
    .map(normalizeEmail)
    .filter((email) => email && email !== "20" && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email));
}

function readWorkbookData() {
  if (!existsSync(WORKBOOK_DATA_PATH)) {
    // Generated by scripts/generate-portal-workbook-access.mjs using exceljs.
    // The source Excel workbooks stay under private-source/portal and are not
    // read directly by the Next.js app bundle.
    return { people: [], accounts: [] } satisfies Required<PortalWorkbookData>;
  }

  try {
    const data = JSON.parse(readFileSync(WORKBOOK_DATA_PATH, "utf8")) as
      | PortalWorkbookData
      | undefined;

    return {
      people: data?.people ?? [],
      accounts: data?.accounts ?? [],
    } satisfies Required<PortalWorkbookData>;
  } catch {
    return { people: [], accounts: [] } satisfies Required<PortalWorkbookData>;
  }
}

function readPeople() {
  const workbookData = readWorkbookData();

  return workbookData.people
    .map((row) => {
      const emails = [
        ...emailList(row.emails?.join(",")),
      ];

      return {
        name: toText(row.name),
        organization: toText(row.organization),
        accountNumber: toAccountNumber(row.accountNumber),
        emails: [...new Set(emails)],
        division: toText(row.division),
        artisanLab: toText(row.artisanLab),
        targetedPrograms: toText(row.targetedPrograms),
        lastOrderShipped: toText(row.lastOrderShipped),
      } satisfies PortalWorkbookPerson;
    })
    .filter((person) => person.accountNumber && person.emails.length > 0);
}

function hasTargetedProgram(value: string, program: string) {
  return value
    .split(",")
    .map((entry) => entry.trim().toLowerCase())
    .includes(program);
}

function readAccounts() {
  const workbookData = readWorkbookData();

  return workbookData.accounts
    .map((row) => ({
      accountName: toText(row.accountName),
      accountNumber: toAccountNumber(row.accountNumber),
      division: toText(row.division),
      salesRep: toText(row.salesRep),
      lastShippedDate: toText(row.lastShippedDate),
      primaryPalPrivatePay: toText(row.primaryPalPrivatePay),
      primaryPalVsp: toText(row.primaryPalVsp),
      lastLabName: toText(row.lastLabName),
      fullAddress: toText(row.fullAddress),
      phoneNumber: toText(row.phoneNumber),
      state: toText(row.state),
      zipCode: toText(row.zipCode),
      modernPkgUsage: toText(row.modernPkgUsage),
      modernFrmUsage: toText(row.modernFrmUsage),
      chemClipUsage: toText(row.chemClipUsage),
      specCheckUsage: toText(row.specCheckUsage),
      tokaiUsage: toText(row.tokaiUsage),
      tier: toText(row.tier),
      ppmJobs: toNumber(row.ppmJobs),
      pmJobs: toNumber(row.pmJobs),
      cmJobs: toNumber(row.cmJobs),
      ppmSales: toNumber(row.ppmSales),
      pmSales: toNumber(row.pmSales),
      cmSales: toNumber(row.cmSales),
      ppmJpd: toNumber(row.ppmJpd),
      pmJpd: toNumber(row.pmJpd),
      cmJpd: toNumber(row.cmJpd),
      ppmNlJobs: toNumber(row.ppmNlJobs),
      pmNlJobs: toNumber(row.pmNlJobs),
      cmNlJobs: toNumber(row.cmNlJobs),
      pmNlSow: toNumber(row.pmNlSow),
      ppmNlSow: toNumber(row.ppmNlSow),
      cmNlSow: toNumber(row.cmNlSow),
      cmSqlJobs: toNumber(row.cmSqlJobs),
      pmSqlJobs: toNumber(row.pmSqlJobs),
      ppmSqlJobs: toNumber(row.ppmSqlJobs),
      ppmVspJobs: toNumber(row.ppmVspJobs),
      pmVspJobs: toNumber(row.pmVspJobs),
      cmVspJobs: toNumber(row.cmVspJobs),
      ppmVspSow: toNumber(row.ppmVspSow),
      pmVspSow: toNumber(row.pmVspSow),
      cmVspSow: toNumber(row.cmVspSow),
      lastShippedDateGlobal: toText(row.lastShippedDateGlobal),
    }))
    .filter((account) => account.accountNumber);
}

const people = readPeople();
const accounts = calculateDerivedMetrics(groupAccountRows(readAccounts()));
const accountsByNumber = new Map(
  accounts.map((account) => [
    normalizePortalAccountNumber(account.accountNumber),
    account,
  ])
);

export function getPortalWorkbookProfileByEmail(
  email: string,
  accountNumber?: string
) {
  const normalizedEmail = normalizeEmail(email);

  if (!normalizedEmail) return undefined;

  const matchingPeople = people.filter((entry) =>
    entry.emails.includes(normalizedEmail)
  );
  const person =
    accountNumber && matchingPeople.length > 0
      ? matchingPeople.find(
          (entry) =>
            normalizePortalAccountNumber(entry.accountNumber) ===
            normalizePortalAccountNumber(accountNumber)
        )
      : matchingPeople[0];

  if (!person) return undefined;

  return {
    person,
    account: accountsByNumber.get(normalizePortalAccountNumber(person.accountNumber)),
  } satisfies PortalWorkbookProfile;
}

export function getPortalWorkbookProfilesByEmail(
  email: string
): PortalWorkbookProfile[] {
  const normalizedEmail = normalizeEmail(email);

  if (!normalizedEmail) return [];

  const accountNumbers = [
    ...new Set(
      people
        .filter((entry) => entry.emails.includes(normalizedEmail))
        .map((entry) => normalizePortalAccountNumber(entry.accountNumber))
    ),
  ];

  const profiles: PortalWorkbookProfile[] = [];

  for (const accountNumber of accountNumbers) {
    const profile = getPortalWorkbookProfileByEmail(
      normalizedEmail,
      accountNumber
    );

    if (profile) profiles.push(profile);
  }

  return profiles;
}

export function getPortalWorkbookAccountsForEmail(email: string) {
  return getAccountsForUser({ email, people, accounts });
}

export function getPortalWorkbookAccountByAccountNumber(accountNumber: string) {
  return accountsByNumber.get(normalizePortalAccountNumber(accountNumber));
}

export function getPortalWorkbookProfileByAccountNumber(accountNumber: string) {
  const person = people.find(
    (entry) =>
      normalizePortalAccountNumber(entry.accountNumber) ===
      normalizePortalAccountNumber(accountNumber)
  );
  const account = getPortalWorkbookAccountByAccountNumber(accountNumber);

  if (!person && !account) return undefined;

  return {
    person: person ?? {
      name: "",
      organization: account?.accountName ?? "",
      accountNumber,
      emails: [],
      division: account?.division ?? "",
      artisanLab: account?.lastLabName ?? "",
      targetedPrograms: "",
      lastOrderShipped: account?.lastShippedDate ?? "",
    },
    account,
  } satisfies PortalWorkbookProfile;
}

export function getPortalWorkbookPeople() {
  return people;
}

export function getPortalWorkbookAccounts() {
  return accounts;
}

export function getPortalWorkbookPeopleByAccountNumber(accountNumber: string) {
  return getUsersForAccount({ accountNumber, people });
}

export function getCustomerTypeCodeForWorkbookProfile(
  profile?: PortalWorkbookProfile
) {
  return (
    profile?.account?.finalCustomerTypeCode ||
    profile?.account?.division ||
    profile?.person.division ||
    ""
  )
    .trim()
    .toUpperCase();
}

export function getCustomerTypeInfoForWorkbookProfile(
  profile?: PortalWorkbookProfile
) {
  return getPortalCustomerTypeInfo(getCustomerTypeCodeForWorkbookProfile(profile));
}

export function personHasSequelRebateInvitation(person?: PortalWorkbookPerson) {
  return Boolean(
    person?.targetedPrograms &&
      hasTargetedProgram(person.targetedPrograms, SEQUEL_REBATE_PROGRAM)
  );
}

export function accountHasSequelRebateInvitation(accountNumber: string) {
  return getPortalWorkbookPeopleByAccountNumber(accountNumber).some(
    personHasSequelRebateInvitation
  );
}

export function profileHasSequelRebateInvitation(
  profile?: PortalWorkbookProfile
) {
  if (!profile) return false;

  if (personHasSequelRebateInvitation(profile.person)) return true;

  return accountHasSequelRebateInvitation(
    profile.account?.accountNumber || profile.person.accountNumber
  );
}
